### PR TITLE
Added the ability to not close popup after smile choosing

### PR DESCRIPTION
**Pull request by delverdev**
It's more convenient to not close popup after smile choosing (it's closing only from outside clicking). However, I've made it optional, so if you want to close popup, you should add 'smilies-close' attribute.

### CODE REVIEW

**Comment by mistic100** [comment]
Why do you use "attrs" instead of the scope ?

Tested with both Angular Strap and Angular UI ?

**Comment by delverdev** [comment]
1. I don't think it matters in this situation.
2. It works only with Angular UI. AngularStrap doesn't support it for now. There are some hacks but I don't think this it's a good idea.

**Comment by mistic100** [comment]
1. yes it does matter, because code consistency is important

2. So I tested with both Angular UI and Angular Strap and the popover never closes with an outside click

3. I can't find any documentation for `popover-trigger="outsideClick"`for Angular Bootstrap

**Comment by mistic100** [comment]
And you implementation breaks the default behaviour. I would prefer

```js
scope: {
   keepOpen: '@smiliesKeepOpen'
},
............
if ($scope.keepOpen === undefined) {
............
}
```

**Comment by delverdev** [comment]
I did as you want.
It doesn't work for you because your repo uses old version of ui-bootstrap when even popover-template works without uib prefix. 
Documentation for outsideClick you can find [here](https://angular-ui.github.io/bootstrap/#/triggers).

**Comment by mistic100** [comment]
I DID updated the dependencies before testing (you forgot to update the dependency in you previous PR https://github.com/mistic100/angular-smilies/commit/4255316e5d718c6e26a607cc9123e0166cf5d84d#diff-0a08a7565aba4405282251491979bb6bL20).

It didn't work because you put "outsideClick" on the wrong template, now with your last changes, it works.

**Pull request merged**
